name: Pre-Commit

on:
  pull-request:

jobs:
  Pre-Commit:
    name: Pre-Commit
    runs-on: ubuntu-latest
    container:
      image: python:3.10.14-slim-bookworm

    steps:
      - name: Install System Deps
        run: |
          apt-get update
          apt-get install -y enchant git gcc make zlib1g-dev libc-dev libffi-dev g++ libxml2 libxml2-dev libxslt-dev libcurl4-openssl-dev libssl-dev libgnutls28-dev

      - uses: actions/checkout@v4

      - name: Install Pre-Commit
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit
          pre-commit install --install-hooks

      - name: Check ALL Files On Branch
        run: |
          pre-commit run --show-diff-on-failure --color=always --all-files
